### ISSUE TITLE
cloud-native-workshop-v2m1-guides/ocp-4.9-jp/migrate-to-jboss-eap.adoc 14.モノリスのデプロイ の内容が全般的に古いように見える。

### ISSUE THREAD

**Issue by ssetoredhat** [team-ohc-jp-place/cloud-native-workshop-v2m1-guides#9]

**Comment by nobusue** [comment]
どのへんが古くなってました? 気づいたところのポインタだけ教えていただければと。

**Comment by ssetoredhat** [comment]
多分全部です。

英語だと1行目が
We’ve pre-installed an application template for use. Click the Start building your application in the Topology view:
で、日本語だと
使用するアプリケーション テンプレート をあらかじめインストールしておきました。 From Catalog をクリックします。
で全く対応が取れていないです。

4.7 -> 4.8の更新分が漏れてるみたいです。ここらへんな気がします。
https://github.com/RedHat-Middleware-Workshops/cloud-native-workshop-v2m1-guides/commit/3b9b82af6550eadf0efc9dce332b06df3ab7a1c1#diff-8470d6e00a2b25b68ee4aa4fa7ec09781e0ff6a398ee990328a015021648c560

**Comment by ssetoredhat** [comment]
fixed.
